- name: Install Nginx on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create /etc/nginx directory if missing
      file:
        path: /etc/nginx
        state: directory
        mode: '0755'

    - name: Ensure nginx.conf exists
      stat:
        path: /etc/nginx/nginx.conf
      register: nginx_conf_stat

    - name: Create default nginx.conf if missing
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user www-data;
          worker_processes auto;
          pid /run/nginx.pid;

          events {
              worker_connections 768;
          }

          http {
              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              access_log /var/log/nginx/access.log;
              error_log /var/log/nginx/error.log;

              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;

              include /etc/nginx/conf.d/*.conf;
          }
      when: nginx_conf_stat.stat.exists == False

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Open HTTP and HTTPS ports in UFW
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - "Nginx HTTP"
        - "Nginx HTTPS"
