---
- name: Install Nginx on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Open HTTP and HTTPS ports in UFW
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - "Nginx HTTP"
        - "Nginx HTTPS"
